# Generated by Django 5.0.6 on 2024-11-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingreso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nombre',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
